// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef table_h
#define table_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Tile.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Progress.H>
#include <FL/Fl_Choice.H>
/**
 Show table to user
*/

class MainWindow : public Fl_Window {
public:
  MainWindow(int X, int Y, int W, int H, const char *L = 0);
  Fl_Button *solve;
  Fl_Input *goal_input;
  Fl_Input *user_input_table;
  Fl_Value_Output *level_output_box;
  Fl_Button *next_button;
  Fl_Button *previous_button;
  Fl_Progress *progress_bar;
  Fl_Choice *method_choices;
  static Fl_Menu_Item menu_method_choices[];
  static Fl_Menu_Item *DFS;
  static Fl_Menu_Item *BFS;
};
#endif
